version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: sudo pip install --egg pyenv
      - run: pyenv update
      - run: pyenv global 2.7.11 3.5.1
      - run: sudo pyenv global 2.7.11 3.5.1
      - run: sudo python setup.py install
      - run: sudo pip install tox
      - run: sudo python setup.py test
      - run: sudo tox

workflows:
  version: 2
  test:
    jobs:
      - build
