version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: |
          pyenv global 2.7.11 3.5.1
          python setup.py install
          pip install tox
          python setup.py test
          tox

workflows:
  version: 2
  test:
    jobs:
      - build
